---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:xtda4664/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: gcr.io/upbeat-flame-320411/echoapp
      tag: prod-5
    replicaCount: 3
