apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.conf.secretName }}
type: {{ .Values.conf.secretType }}
data:
  MONGODBURL: {{- printf "\"mongodb://%s:%s@%s.%s.svc.%s/%s\"" .Values.mongodb.auth.username .Values.mongodb.auth.password .Values.service.name .Release.Namespace  .Values.clusterdomain .Values.mongodb.auth.database  | b64enc | quote | indent 2 }}
